- spi.c
Support for SPI operations has been fixed by adding support for new layout of SPI registers compatible with YANGTZEE FCH.
> Flash issue fix

- LICENSE
- include/flash_access.h
- include/sec_reg_menu.h
- spi/spi_flash_internal.h
- utils/flash_access.c
- utils/sec_reg_menu.c
Every source file of code is released under GNU GPLv2.
> add LICENSE file

- CHANGELOG.md
> CHANGELOG: update to v4.6.8

- CHANGELOG.md
> CHANGELOG.md: add v4.6.10 release info

- utils/sec_reg_menu.c
Signed-off-by: Krystian Hebel <krystian.hebel@3mdeb.com>
> utils/sec_reg_menu.c: fix printing of erased serial

- CHANGELOG.md
> CHANGELOG.md: add v4.6.11 release info

- spi/winbond.c
I've tested this on a board with a W25Q64JV. It should also work with other Winbond chips, while it will have no effect on non-Winbond chips.
- SPI write protection can be enabled
- With SPI write protection enabled, and the Write-Protect jumper is closed, no status registers can be modified, and no memory can be erased or written.
- With SPI write protection enable and the WP jumper open, write protection can be disabled.
- One-time programmable "lock" registers can still be enabled.
---
The "new" instruction set doesn't work reliably in some cases.
Use the backwards-compatible 3-byte Write Status Register instruction, and
remove usage of Status Register 3.
This fixes SPI write protection on some boards.
NOTE: SRP0 and /WP pin are not documented for W25Q64JV.
Despite this, it is tested …
> spi/winbond: use "legacy" instruction set

- CHANGELOG.md
> CHANGELOG.md: add v4.6.12 release info

- sortbootorder.c
> sortbootorder.c: add boost runtime configuration

- sortbootorder.c
> sortbootorder.c: fix build for apu1

- README.md
- sortbootorder.c
Signed-off-by: Michał Witwicki <michal.witwicki@3mdeb.com>
> sortbootorder.c: add IOMMU management

- CHANGELOG.md
Signed-off-by: Marek Kasiewicz <marek.kasiewicz@3mdeb.com>
> v4.6.19 release

- sortbootorder.c
Signed-off-by: Mateusz Kowalski <mateusz.kowalski@3mdeb.com>
> sortbootorder.c: fix boot menu uart entry

- README.md
Signed-off-by: Mateusz Kowalski <mateusz.kowalski@3mdeb.com>
> README.md: Replace old uart boot menu entries with new ones

- README.md
Signed-off-by: Krystian Hebel <krystian.hebel@3mdeb.com>
> README.md: clarify bootorder file location

- include/rtc_clock_menu.h
- sortbootorder.c
- utils/rtc_clock_menu.c
Signed-off-by: Michał Kopeć <michal.kopec@3mdeb.com>
> Add RTC clock menu

- CHANGELOG.md
Signed-off-by: Michał Kopeć <michal.kopec@3mdeb.com>
> Rel v4.6.23

- sortbootorder.c
Signed-off-by: Michał Kopeć <michal.kopec@3mdeb.com>
> Hide iPXE on APU7

- CHANGELOG.md
Signed-off-by: Michał Kopeć <michal.kopec@3mdeb.com>
> CHANGELOG.md: add v4.6.24 release info

- sortbootorder.c
The following changes are necessary due to the removal of the legacy CBFS API from coreboot in February 2024.
The bootorder fetching logic has been refactored in this commit to enhance code readability and maintainability. The changes include:
- Replacing `cbfs_get_handle` and `cbfs_get_file_content` with `cbfs_map` for mapping the bootorder file.
- Removing redundant code and simplifying the logic for fetching the bootorder from CBFS.
- Adding `cbfs_unmap` calls to ensure proper unmapping of the bootorder data.
- Consolidating error checks and aligning the bootorder file handling with the new mapping approach.
These changes streamline the bootorder fetching process and ensure better resource management.
> Support for the new CBFS API
